import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  topBackground: {
    backgroundColor: '#4CA687',
    height: height * 0.44,
    borderBottomLeftRadius: width * 0.5,
    borderBottomRightRadius: width * 0.12,
    paddingHorizontal: 22,
    position: 'relative',
    overflow: 'hidden',
  },
  curveBacking: {
    position: 'absolute',
    top: -40,
    right: -30,
    width: width * 0.8,
    height: width * 0.8,
    borderRadius: width * 0.4,
    backgroundColor: '#57B797',
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  cloudBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  utensilCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  utensilsIcon: {
    fontSize: 14,
  },
  cloudBadgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2D3F76',
  },
  skipButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  skipText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  leftTealLeaf: {
    position: 'absolute',
    bottom: 24,
    left: 20,
  },
  leafSegment: {
    backgroundColor: '#2D8A68',
    borderRadius: 10,
  },
  leafA: {
    width: 24,
    height: 12,
    transform: [{ rotate: '-25deg' }],
    marginBottom: 4,
  },
  leafB: {
    width: 18,
    height: 10,
    transform: [{ rotate: '15deg' }],
  },
  rightZigzag: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    opacity: 0.4,
  },
  zigzagSymbol: {
    fontSize: 18,
    color: '#FFFFFF',
  },

  // ILLUSTRATION SECTION
  illustrationSection: {
    height: height * 0.28,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -height * 0.12,
    zIndex: 5,
  },
  illustrationImage: {
    width: width * 0.78,
    height: height * 0.28,
  },

  // CONTENT SECTION
  contentSection: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 8,
    justifyContent: 'space-between',
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  dot: {
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  activeDot: {
    width: 28,
    backgroundColor: '#4CA687',
  },
  inactiveDot: {
    width: 8,
    backgroundColor: '#CBD5E1',
  },
  textContainer: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  greetingText: {
    fontSize: 32,
    fontWeight: '800',
    color: '#2D3F76',
    marginRight: 8,
    letterSpacing: -0.5,
  },
  emoji: {
    fontSize: 28,
  },
  mainTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: '#2D3F76',
    marginBottom: 12,
    letterSpacing: -0.5,
  },
  descriptionText: {
    fontSize: 15,
    lineHeight: 23,
    color: '#2D3F76',
    opacity: 0.8,
    fontWeight: '400',
  },
  categoryHeading: {
    fontSize: 26,
    fontWeight: '800',
    color: '#2D3F76',
    lineHeight: 34,
    marginBottom: 20,
    letterSpacing: -0.4,
  },
  categoriesGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  categoryCard: {
    alignItems: 'center',
    width: (width - 60) / 4,
  },
  categoryIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 2,
    borderColor: '#FECDD3',
  },
  categoryEmoji: {
    fontSize: 26,
  },
  categoryLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2D3F76',
    textAlign: 'center',
  },
  ctaContainer: {
    alignItems: 'center',
    marginTop: 16,
  },
  ctaButton: {
    backgroundColor: '#4CA687',
    width: '80%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  ctaButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // LOGIN SCREEN STYLES
  loginScrollContainer: {
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
  },
  loginTopBackground: {
    backgroundColor: '#4CA687',
    height: height * 0.22,
    borderBottomLeftRadius: width * 0.5,
    borderBottomRightRadius: width * 0.12,
    paddingHorizontal: 22,
    position: 'relative',
    overflow: 'hidden',
  },
  loginCurveBacking: {
    position: 'absolute',
    top: -30,
    right: -20,
    width: width * 0.7,
    height: width * 0.7,
    borderRadius: width * 0.35,
    backgroundColor: '#57B797',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    marginTop: 4,
  },
  backArrowText: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  loginBodyContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 28,
  },
  loginHeading: {
    fontSize: 34,
    fontWeight: '800',
    color: '#2D3F76',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  loginSubheading: {
    fontSize: 15,
    color: '#2D3F76',
    opacity: 0.75,
    marginBottom: 32,
    fontWeight: '400',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    height: 58,
    paddingHorizontal: 16,
    marginBottom: 18,
  },
  inputIconBox: {
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputIconText: {
    fontSize: 18,
  },
  inputSeparator: {
    width: 1,
    height: 24,
    backgroundColor: '#CBD5E1',
    marginHorizontal: 12,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D3F76',
    fontWeight: '500',
  },
  checkIcon: {
    fontSize: 18,
    color: '#10B981',
    fontWeight: 'bold',
  },
  eyeIconButton: {
    padding: 6,
  },
  eyeIconText: {
    fontSize: 18,
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-start',
    marginBottom: 28,
    marginTop: 2,
  },
  forgotPasswordText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2D3F76',
  },
  proceedButton: {
    backgroundColor: '#4CA687',
    width: '100%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
    marginBottom: 26,
  },
  proceedButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 26,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  dividerText: {
    fontSize: 14,
    color: '#64748B',
    paddingHorizontal: 14,
    fontWeight: '500',
  },
  otpButton: {
    backgroundColor: '#8EA1B4',
    width: '100%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8EA1B4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 32,
  },
  otpButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  registerFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 'auto',
  },
  dontHaveAccountText: {
    fontSize: 15,
    color: '#2D3F76',
    fontWeight: '500',
  },
  registerLinkText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#4CA687',
  },

  // BOTTOM SHEET OTP MODAL STYLES
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'flex-end',
  },
  modalOverlayTouchable: {
    flex: 1,
  },
  bottomSheetContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 28,
    paddingTop: 32,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 16,
  },
  closeCircleButton: {
    position: 'absolute',
    top: -24,
    right: 24,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FF3B30',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 20,
  },
  closeCrossText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#2D3F76',
    marginBottom: 24,
    letterSpacing: -0.3,
  },
  modalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    height: 58,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  otpSubtitle: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 16,
    lineHeight: 20,
  },
  boldEmail: {
    fontWeight: '700',
    color: '#2D3F76',
  },
  resendContainer: {
    alignSelf: 'flex-end',
    marginBottom: 20,
    marginTop: -10,
  },
  resendText: {
    fontSize: 13,
    color: '#64748B',
  },
  resendBold: {
    fontWeight: '700',
    color: '#4CA687',
  },
  modalProceedButton: {
    backgroundColor: '#4CA687',
    width: '100%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  modalProceedButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // OTP VERIFICATION SCREEN STYLES
  otpTopBackground: {
    backgroundColor: '#FDE047',
    height: height * 0.22,
    borderBottomLeftRadius: width * 0.5,
    borderBottomRightRadius: width * 0.12,
    paddingHorizontal: 22,
    position: 'relative',
    overflow: 'hidden',
  },
  otpCurveBacking: {
    position: 'absolute',
    top: -30,
    right: -20,
    width: width * 0.75,
    height: width * 0.75,
    borderRadius: width * 0.375,
    backgroundColor: '#FEF08A',
  },
  otpCurveBackingSecondary: {
    position: 'absolute',
    top: 40,
    left: -40,
    width: width * 0.6,
    height: width * 0.6,
    borderRadius: width * 0.3,
    backgroundColor: '#FACC15',
    opacity: 0.35,
  },
  otpBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    marginTop: 4,
  },
  otpBackArrowText: {
    fontSize: 24,
    color: '#1E293B',
    fontWeight: '700',
  },
  otpBodyContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 32,
  },
  otpHeading: {
    fontSize: 34,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 10,
    letterSpacing: -0.5,
  },
  otpSubheading: {
    fontSize: 15,
    color: '#475569',
    lineHeight: 23,
    marginBottom: 36,
    fontWeight: '400',
  },
  boldEmailText: {
    fontWeight: '700',
    color: '#1E293B',
  },
  otpInputsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  otpBox: {
    width: (width - 56 - 36) / 4,
    height: (width - 56 - 36) / 4,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    fontSize: 26,
    fontWeight: '700',
    color: '#1E293B',
  },
  otpBoxFocused: {
    borderColor: '#4CA687',
    backgroundColor: '#FFFFFF',
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  otpBoxFilled: {
    borderColor: '#4CA687',
    backgroundColor: '#F0FDF4',
  },
  timerContainer: {
    alignItems: 'center',
    marginBottom: 36,
  },
  timerText: {
    fontSize: 15,
    color: '#64748B',
    fontWeight: '500',
  },
  timerHighlight: {
    fontWeight: '700',
    color: '#1E293B',
  },
  resendLinkText: {
    fontSize: 15,
    color: '#64748B',
  },
  resendBoldText: {
    fontWeight: '700',
    color: '#4CA687',
  },
  verifyButton: {
    backgroundColor: '#4CA687',
    width: '100%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  // REGISTER SCREEN STYLES
  registerTopBackground: {
    backgroundColor: '#FDE047',
    height: height * 0.22,
    borderBottomLeftRadius: width * 0.5,
    borderBottomRightRadius: width * 0.12,
    paddingHorizontal: 22,
    position: 'relative',
    overflow: 'hidden',
  },
  registerCurveBacking: {
    position: 'absolute',
    top: -30,
    right: -20,
    width: width * 0.75,
    height: width * 0.75,
    borderRadius: width * 0.375,
    backgroundColor: '#FEF08A',
  },
  registerCurveBackingSecondary: {
    position: 'absolute',
    top: 40,
    left: -40,
    width: width * 0.6,
    height: width * 0.6,
    borderRadius: width * 0.3,
    backgroundColor: '#FACC15',
    opacity: 0.35,
  },
  registerBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    marginTop: 4,
  },
  registerBackArrowText: {
    fontSize: 24,
    color: '#1E293B',
    fontWeight: '700',
  },
  registerBodyContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 32,
  },
  registerHeading: {
    fontSize: 34,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  registerSubheading: {
    fontSize: 15,
    color: '#475569',
    marginBottom: 32,
    fontWeight: '400',
  },
  termsNoticeText: {
    fontSize: 13,
    color: '#64748B',
    lineHeight: 20,
    marginBottom: 28,
    marginTop: 6,
  },
  termsHighlightText: {
    color: '#EA580C',
    fontWeight: '600',
  },
  darkProceedButton: {
    backgroundColor: '#27272A',
    width: '100%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#27272A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
    marginBottom: 36,
  },
  darkProceedButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  socialDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 28,
  },
  socialDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  socialDividerText: {
    fontSize: 14,
    color: '#64748B',
    paddingHorizontal: 14,
    fontWeight: '500',
  },
  socialButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    marginBottom: 36,
  },
  socialCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  socialIconText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
  },
  socialIconTextSmall: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  loginLinkHighlightText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#EA580C',
  },
  sectionDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
    paddingHorizontal: 22,
  },
  sectionDividerLine: {
    flex: 1,
    height: 1.5,
    backgroundColor: '#E2E8F0',
  },
  sectionDividerText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
    paddingHorizontal: 16,
  },

  // REGISTER DETAILS (STEP 1/4) STYLES
  detailsScrollContainer: {
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
  },
  detailsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
  },
  detailsBackTouch: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailsBackArrow: {
    fontSize: 26,
    color: '#1E293B',
    fontWeight: '700',
    marginRight: 16,
  },
  detailsHeaderTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1E293B',
    letterSpacing: -0.5,
  },
  stepCounterBox: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  stepNumText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1E293B',
  },
  stepDenomText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#94A3B8',
  },
  detailsBodyContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 10,
  },
  inputVerifiedContainer: {
    borderColor: '#14B8A6',
    borderWidth: 1.5,
    backgroundColor: '#F8FAFC',
  },
  checkCircleBox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkIconText: {
    fontSize: 18,
    color: '#14B8A6',
    fontWeight: 'bold',
  },
  genderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 36,
    marginTop: 12,
    marginBottom: 20,
    paddingLeft: 4,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: '#FFFFFF',
  },
  radioCircleSelected: {
    borderColor: '#14B8A6',
    backgroundColor: '#14B8A6',
  },
  radioCheckMark: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  radioLabelText: {
    fontSize: 16,
    color: '#1E293B',
    fontWeight: '600',
  },
  passwordDescriptionText: {
    fontSize: 15,
    color: '#475569',
    lineHeight: 22,
    marginBottom: 32,
    fontWeight: '400',
  },

  // REGISTER PHOTO (STEP 3/4) STYLES
  avatarContainerCenter: {
    alignItems: 'center',
    marginBottom: 32,
  },
  avatarCardBox: {
    width: width * 0.58,
    height: width * 0.58,
    borderRadius: 24,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 24,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
  },
  avatarPlaceholderBox: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  avatarHeadCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#475569',
    marginBottom: 8,
  },
  avatarBodyCurve: {
    width: 110,
    height: 55,
    borderTopLeftRadius: 55,
    borderTopRightRadius: 55,
    backgroundColor: '#475569',
  },
  uploadOptionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 40,
  },
  uploadOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  uploadOptionIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  uploadOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },

  // REGISTER DOCUMENTS (STEP 4/4) STYLES
  bulletListContainer: {
    marginBottom: 24,
  },
  bulletItemText: {
    fontSize: 13,
    color: '#334155',
    lineHeight: 20,
    fontWeight: '500',
    marginBottom: 4,
  },
  docUploadCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    marginBottom: 16,
  },
  docCardUploaded: {
    borderColor: '#2DD4BF',
    backgroundColor: '#F0FDFA',
  },
  docCardError: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  docCardLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  upCircleTeal: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#0D9488',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: '#FFFFFF',
  },
  upCircleRed: {
    borderColor: '#EF4444',
  },
  upArrowTextTeal: {
    fontSize: 20,
    color: '#0D9488',
    fontWeight: 'bold',
  },
  upArrowTextRed: {
    color: '#EF4444',
  },
  docTitleTeal: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0D9488',
  },
  docTitleRed: {
    color: '#EF4444',
  },
  docSubText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  uploadedBadge: {
    backgroundColor: '#2DD4BF',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  uploadedBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  warningTriangleIcon: {
    fontSize: 22,
  },
  thumbnailWrapper: {
    position: 'relative',
    width: 80,
    height: 60,
    borderRadius: 10,
    overflow: 'visible',
    marginBottom: 20,
  },
  docThumbnailImage: {
    width: 80,
    height: 60,
    borderRadius: 10,
  },
  redCrossBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  redCrossText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  infoSectionHeading: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 10,
  },
  licenseInfoInputsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 24,
  },
  infoIconSymbol: {
    fontSize: 14,
    color: '#94A3B8',
    fontWeight: '600',
  },
  docErrorText: {
    color: '#EF4444',
    fontSize: 13,
    fontWeight: '500',
    marginTop: -8,
    marginBottom: 16,
  },
  cardSeparatorLine: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: 16,
  },
  redSubmitPillButton: {
    backgroundColor: '#FF3B00',
    width: '100%',
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF3B00',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  redSubmitButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // POST-REGISTRATION STATUS SCREENS STYLES
  statusScreenContainer: {
    backgroundColor: '#FFFFFF',
    position: 'relative',
  },
  confettiContainer: {
    ...StyleSheet.absoluteFill,
    pointerEvents: 'none',
    zIndex: 1,
  },
  confettiDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  confettiRect: {
    position: 'absolute',
    width: 12,
    height: 6,
    borderRadius: 2,
  },
  floatingSymbol: {
    position: 'absolute',
    fontSize: 24,
    color: '#FF3B00',
    opacity: 0.35,
    fontWeight: 'bold',
  },
  floatingSymbolRed: {
    position: 'absolute',
    fontSize: 22,
    color: '#FF3B00',
    opacity: 0.4,
  },
  statusScrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    zIndex: 2,
  },
  successCircleBadgeOuter: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(20, 184, 166, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 36,
  },
  successCircleBadgeInner: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#14B8A6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#14B8A6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  successCheckmarkIcon: {
    fontSize: 70,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  notVerifiedBadgeOuter: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 36,
  },
  notVerifiedBadgeInner: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  notVerifiedCrossIcon: {
    fontSize: 64,
    color: '#FFFFFF',
    fontWeight: '800',
  },
  underProgressIllustrationBox: {
    width: width * 0.75,
    height: height * 0.26,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
  },
  underProgressScooterImg: {
    width: '100%',
    height: '100%',
  },
  titleWavyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    gap: 8,
  },
  wavyDecorationText: {
    fontSize: 22,
    color: '#FF3B00',
  },
  statusTitleRed: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FF3B00',
    letterSpacing: -0.5,
  },
  statusDescriptionText: {
    fontSize: 15,
    color: '#475569',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 40,
    fontWeight: '400',
    paddingHorizontal: 12,
  },
  statusButtonsContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 16,
    marginTop: 'auto',
  },
  secondaryTextBtn: {
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  secondaryTextBtnLabel: {
    fontSize: 15,
    color: '#64748B',
    fontWeight: '600',
  },

  // HOME / PROFILE DASHBOARD STYLES
  homeScrollContent: {
    paddingBottom: 110,
    backgroundColor: '#FAFAFA',
  },
  homeTopHeader: {
    backgroundColor: '#4CA687',
    paddingHorizontal: 22,
    paddingBottom: 70,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
  },
  homeHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeUtensilCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  homeBrandTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  homeAvailabilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  homeAvailableText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: 4,
  },
  homeBellTouch: {
    position: 'relative',
    padding: 6,
  },
  homeBellBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#4CA687',
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeBellBadgeText: {
    color: '#FFFFFF', 
    fontSize: 11,
    fontWeight: 'bold',
  },

  // PROFILE OVERLAPPING CARD STYLES
  homeProfileCardWrapper: {
    marginTop: -50,
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  homeProfileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  homeAvatarBox: {
    position: 'relative',
    marginRight: 18,
  },
  homeAvatarImage: {
    width: 68,
    height: 68,
    borderRadius: 34,
  },
  homeVerifiedBadge: {
    position: 'absolute',
    bottom: -2,
    left: -2,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#38BDF8',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  homeVerifiedCheckText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  homeProfileInfo: {
    justifyContent: 'center',
  },
  homeWelcomeTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#2D3F76',
    marginBottom: 4,
  },
  homeEditProfileText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4CA687',
  },

  // TABS ROW STYLES
  homeTabsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    gap: 24,
    marginBottom: 20,
  },
  homeTabItem: {
    position: 'relative',
    paddingBottom: 8,
  },
  homeTabText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748B',
  },
  homeTabTextActive: {
    color: '#2D3F76',
    fontWeight: '800',
  },
  homeTabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#4CA687',
    borderRadius: 1.5,
  },

  // TAB CONTENT STYLES
  homeTabContentContainer: {
    paddingHorizontal: 24,
  },
  homeStatCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
  },
  homeStatTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  homeStatTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2D3F76',
  },
  homeStatSubtitle: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  homeStatGrowthBadge: {
    backgroundColor: '#F0FDFA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CCFBF1',
  },
  homeStatGrowthText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4CA687',
  },
  homeStatBottomRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  homeStatMetaLabel: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500',
    marginBottom: 2,
  },
  homeStatMetaVal: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2D3F76',
  },
  homeStatAmountVal: {
    fontSize: 22,
    fontWeight: '800',
    color: '#2D3F76',
  },

  // CHART CONTAINER STYLES
  homeChartContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 20,
  },
  homeChartFiltersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 24,
  },
  homeChartFilterBtn: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  homeChartFilterBtnActive: {
    backgroundColor: '#4CA687',
    borderColor: '#4CA687',
  },
  homeChartFilterText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  homeChartFilterTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  homeChartGridWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 190,
    marginBottom: 16,
  },
  homeChartYAxis: {
    height: 160,
    justifyContent: 'space-between',
    paddingRight: 10,
    alignItems: 'flex-end',
    marginBottom: 20,
  },
  homeChartAxisText: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500',
  },
  homeChartPlotArea: {
    flex: 1,
    height: 190,
    position: 'relative',
  },
  homeChartYAxisLine: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 24,
    width: 1.5,
    backgroundColor: '#E2E8F0',
  },
  homeChartXAxisLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 24,
    height: 1.5,
    backgroundColor: '#E2E8F0',
  },
  homeChartBarsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: 190,
    paddingLeft: 8,
  },
  homeBarCol: {
    alignItems: 'center',
    width: (width - 120) / 4,
  },
  homeBarTrack: {
    width: 32,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  homeBarFill: {
    width: 32,
    backgroundColor: '#4CA687',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  homeBarLabel: {
    fontSize: 12,
    color: '#475569',
    marginTop: 8,
    fontWeight: '600',
  },
  homeChartDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
  },
  homeChartDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E2E8F0',
  },
  homeChartDotActive: {
    backgroundColor: '#4CA687',
    width: 10,
    height: 10,
    borderRadius: 5,
  },

  // BOTTOM FLOATING NAV BAR STYLES
  homeBottomNavBarWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    backgroundColor: 'transparent',
    pointerEvents: 'box-none',
  },
  homeBottomNavBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: width - 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 36,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  homeBottomNavTab: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  homeBottomNavIcon: {
    fontSize: 22,
    opacity: 0.6,
    marginBottom: 2,
  },
  homeBottomNavIconActive: {
    opacity: 1,
  },
  homeBottomNavLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  homeBottomNavLabelActive: {
    color: '#4CA687',
    fontWeight: '700',
  },

  // RANGE TAB STYLES
  rangeInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 32,
  },
  rangeRowTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  rangeIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0FDFA',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  rangePinEmoji: {
    fontSize: 20,
  },
  rangeRowInfo: {
    flex: 1,
  },
  rangeRowTitleRed: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4CA687',
    marginBottom: 2,
  },
  rangeRowSubtitle: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '400',
  },
  rangeDistanceVal: {
    fontSize: 14,
    color: '#2D3F76',
    fontWeight: '700',
  },
  rangeArrowRight: {
    fontSize: 20,
    color: '#64748B',
    fontWeight: 'bold',
    marginLeft: 8,
  },
  rangeDividerLine: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: 14,
  },

  // GAUGE DIAL STYLES
  rangeGaugeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  rangeGaugeOuterRing: {
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#4CA687',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  rangeGaugeMiddleRing: {
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  gaugeDotItem: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeDotSelected: {
    backgroundColor: '#FFFFFF',
    transform: [{ scale: 1.15 }],
  },
  gaugeKnobDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    borderWidth: 3,
    borderColor: '#4CA687',
  },
  gaugeKnobInnerBlack: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2D3F76',
  },
  rangeGaugeInnerCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  rangeGaugeUnitText: {
    fontSize: 13,
    color: '#94A3B8',
    fontWeight: '600',
    marginBottom: -2,
  },
  rangeGaugeValueText: {
    fontSize: 38,
    fontWeight: '800',
    color: '#2D3F76',
  },

  // LOCATION PICKER SCREEN STYLES
  locationHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F7',
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  locationBackTouch: {
    padding: 6,
    marginRight: 8,
  },
  locationBackArrowText: {
    fontSize: 26,
    color: '#2D3F76',
    fontWeight: 'bold',
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D3F76',
    paddingVertical: 8,
    fontWeight: '500',
  },
  locationHeaderRightIconBox: {
    paddingLeft: 8,
  },

  // LOCATION ACTION PILL STYLES
  locationActionPillContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
  },
  useCurrentLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4CA687',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 28,
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  useCurrentLocationGpsIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  useCurrentLocationBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },

  // LOCATION SUGGESTIONS LIST STYLES
  locationSuggestionsList: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  locationSectionHeaderLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.5,
    marginBottom: 16,
    marginTop: 10,
  },
  locationSuggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  locationSuggestionIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  locationSuggestionTextCol: {
    flex: 1,
  },
  locationSuggestionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3F76',
    marginBottom: 2,
  },
  locationSuggestionSubtitle: {
    fontSize: 13,
    color: '#64748B',
    lineHeight: 18,
  },

  // ORDERS SCREEN STYLES
  orderHistoryHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  orderHistoryHeaderBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  orderLiveBannerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  orderLiveBannerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  orderNoPillBadge: {
    backgroundColor: '#2D3F76',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
  },
  orderNoPillBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  orderTimeLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orderTimeLeftText: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
  },
  orderStatusReadyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3F76',
    marginBottom: 14,
  },
  orderReadyBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  readyToPickupTag: {
    backgroundColor: '#E6F4F1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  readyToPickupTagText: {
    color: '#4CA687',
    fontSize: 13,
    fontWeight: '700',
  },
  orderBannerDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activeTabRedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
    marginLeft: 4,
    marginBottom: 8,
  },
  emptyOrdersContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyOrdersText: {
    fontSize: 15,
    color: '#64748B',
    fontWeight: '600',
  },
  orderCardItemContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
  },
  orderCardTopRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  orderPinCol: {
    alignItems: 'center',
    marginRight: 12,
    paddingTop: 2,
  },
  orderDottedConnectorLine: {
    width: 1,
    height: 36,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    marginVertical: 4,
  },
  orderAddressCol: {
    flex: 1,
  },
  orderRestaurantRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  orderRestaurantTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#2D3F76',
    marginBottom: 2,
  },
  orderAddressSubtitle: {
    fontSize: 13,
    color: '#64748B',
  },
  orderAmountValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2D3F76',
  },
  orderCodTagText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4CA687',
    marginTop: 2,
  },
  orderDestinationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orderHomeTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2D3F76',
    marginBottom: 2,
  },
  orderDistanceValText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2D3F76',
  },
  orderItemsSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
  },
  orderItemsSummaryText: {
    flex: 1,
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
    fontWeight: '500',
  },
  orderTimestampsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: 16,
  },
  orderTimeBlock: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orderTimeMetaLabel: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '500',
  },
  orderTimeMetaValue: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2D3F76',
    marginTop: 1,
  },
  orderActionButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  orderDeclineBtn: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  orderDeclineBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  orderAcceptBtn: {
    backgroundColor: '#4CA687',
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: '#4CA687',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  orderAcceptBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },

  // ACTIVE ORDER SPECIFIC STYLES
  orderNavCircleBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1.5,
    borderColor: '#2D3F76',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  orderNavCircleIcon: {
    fontSize: 18,
    color: '#2D3F76',
  },
  activeOrderActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  activeRibbonCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4CA687',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    marginLeft: -18,
  },
  activeRibbonCallText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 6,
  },
  activeDetailsTextLink: {
    fontSize: 15,
    fontWeight: '700',
    color: '#4CA687',
  },

  // MAP SCREEN STYLES
  mapScreenContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  embeddedMapContainer: {
    height: 480,
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 20,
    position: 'relative',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  embeddedMapCanvas: {
    flex: 1,
    position: 'relative',
  },
  mapHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  mapHeaderBackTouch: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  mapHeaderBackArrow: {
    fontSize: 22,
    color: '#1E293B',
    fontWeight: '700',
  },
  mapHeaderTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1E293B',
    letterSpacing: -0.3,
  },
  mapViewContainer: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  mapExpandBtn: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 10,
  },
  mapLocationTargetBtn: {
    position: 'absolute',
    bottom: 180,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 10,
  },
  mapFloatingCard: {
    position: 'absolute',
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 12,
    zIndex: 20,
  },
  mapLocationHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  mapLocationRedPinBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  mapLocationRedPinIcon: {
    fontSize: 16,
  },
  mapLocationTextCol: {
    flex: 1,
  },
  mapLocationTitleRed: {
    fontSize: 15,
    fontWeight: '700',
    color: '#EF4444',
    marginBottom: 2,
  },
  mapLocationSubtitle: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },
  mapStatsYellowBox: {
    backgroundColor: '#FDE047',
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
  },
  mapStatCol: {
    flex: 1,
    alignItems: 'flex-start',
  },
  mapStatValRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  mapStatValueText: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1E293B',
  },
  mapStatKmUnit: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    marginLeft: 2,
  },
  mapStatLabelText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    marginTop: 2,
  },
  mapStatDividerLine: {
    width: 1,
    height: 38,
    backgroundColor: 'rgba(30, 41, 59, 0.15)',
    marginHorizontal: 16,
  },
});

